# ================================
# Netlify â€” Build & Runtime config
# ================================

[build]
command = "npm run build"
publish  = ".next"

[build.environment]
NEXT_PUBLIC_API_BASE = "/.netlify/functions/api-proxy"

NEXT_PUBLIC_STRIPE_MONTHLY_5 = "https://buy.stripe.com/14A7sM2pzdaY5Kd4nc4Ja03"
NEXT_PUBLIC_STRIPE_DON_5      = "https://buy.stripe.com/6oU00kfclc6U3C5g5U4Ja02"
NEXT_PUBLIC_STRIPE_DON_10     = "https://buy.stripe.com/5kQ3cw0hr1sgdcFcTI4Ja00"
NEXT_PUBLIC_STRIPE_DON_20     = "https://buy.stripe.com/28E4gA8NXfj60pT9Hw4Ja01"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[headers]]
for = "/*"
  [headers.values]
  Content-Security-Policy = "frame-ancestors 'self' https://velo-paris.fr https://*.velo-paris.fr"
  Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
for = "/_next/static/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"
