# ui/netlify.toml
[build]
command = "npm run build"
publish = ".next"

[build.environment]
NEXT_PUBLIC_API_BASE = "https://velib-api-160046094975.europe-west1.run.app"
NEXT_PUBLIC_API_TOKEN = "6z3TKcP;vW?3X3g(@s9D)7-Rie+5!9Gu"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
from = "/api/*"
to = "https://velib-api-160046094975.europe-west1.run.app/:splat"
status = 200
force = true

[[headers]]
for = "/api/*"
  [headers.values]
  Cache-Control = "public, max-age=0, s-maxage=60, stale-while-revalidate=300"
